import { Category, Platform, Portfolio, TechStack, DesignTheme } from '@/types/portfolio';
import {
  DESIGN_THEMES,
  FEATURES,
  TECH_STACKS,
  SCREENS,
  USAGE_STEPS,
  DESCRIPTIONS
} from '@/data/constants';

export function generateUUID(): string {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
    const r = Math.random() * 16 | 0;
    const v = c === 'x' ? r : (r & 0x3 | 0x8);
    return v.toString(16);
  });
}

export function getRandomItems<T>(array: T[], min: number, max: number): T[] {
  const count = Math.floor(Math.random() * (max - min + 1)) + min;
  const shuffled = [...array].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}

export function getRandomItem<T>(array: T[]): T {
  return array[Math.floor(Math.random() * array.length)];
}

export function generateDesignTheme(platform: Platform): DesignTheme {
  const themes = DESIGN_THEMES[platform] || DESIGN_THEMES.web;
  return getRandomItem(themes);
}

export function generateFeatures(platform: Platform): string[] {
  const features = FEATURES[platform] || FEATURES.web;
  return getRandomItems(features, 6, 10);
}

export function generateTechStack(platform: Platform): TechStack {
  const stacks = TECH_STACKS[platform] || TECH_STACKS.web;
  const result: TechStack = {};

  for (const [key, values] of Object.entries(stacks)) {
    result[key as keyof TechStack] = getRandomItem(values as string[]);
  }

  return result;
}

export function generateScreens(platform: Platform): string[] {
  return SCREENS[platform] || SCREENS.web;
}

export function generateUsageSteps(platform: Platform): string[] {
  return USAGE_STEPS[platform] || USAGE_STEPS.web;
}

export function generateDescription(categoryId: string, customDesc?: string): string {
  if (customDesc && customDesc.trim()) {
    return customDesc.trim();
  }

  const descriptions = DESCRIPTIONS[categoryId] || DESCRIPTIONS.productivity;
  return getRandomItem(descriptions);
}

export function generatePortfolio(
  number: number,
  name: string,
  category: Category,
  platform: Platform,
  customDescription?: string
): Portfolio {
  const id = generateUUID();
  const now = new Date().toISOString();

  return {
    id,
    number,
    name,
    category: {
      id: category.id,
      name: category.name,
      icon: category.icon
    },
    platform,
    description: generateDescription(category.id, customDescription),
    designTheme: generateDesignTheme(platform),
    features: generateFeatures(platform),
    techStack: generateTechStack(platform),
    screens: generateScreens(platform),
    usageSteps: generateUsageSteps(platform),
    version: '1.0.0',
    createdAt: now
  };
}

export function generateMarkdown(portfolio: Portfolio): string {
  const techStackStr = Object.entries(portfolio.techStack)
    .map(([key, value]) => `- **${key}**: ${value}`)
    .join('\n');

  const featuresStr = portfolio.features
    .map(f => `- ${f}`)
    .join('\n');

  const screensStr = portfolio.screens
    .map((s, i) => `${i + 1}. ${s}`)
    .join('\n');

  const usageStr = portfolio.usageSteps.join('\n');

  return `# ${portfolio.name}

## 기본 정보

| 항목 | 내용 |
|------|------|
| 분야 | ${portfolio.category.name} |
| 플랫폼 | ${portfolio.platform.toUpperCase()} |
| 버전 | ${portfolio.version} |
| 생성일 | ${new Date(portfolio.createdAt).toLocaleDateString('ko-KR')} |

## 프로젝트 설명

${portfolio.description}

## 디자인 테마

**${portfolio.designTheme.name}**
- Background: ${portfolio.designTheme.bg}
- Text: ${portfolio.designTheme.text}
- Accent: ${portfolio.designTheme.accent}

## 핵심 기능

${featuresStr}

## 기술 스택

${techStackStr}

## 화면 구성

${screensStr}

## 사용 방법

${usageStr}

---

> Portfolio #${portfolio.number}
> Generated by Portfolio Generator
`;
}

export async function generateDocxContent(portfolio: Portfolio): Promise<Blob> {
  const {
    Document,
    Paragraph,
    TextRun,
    Table,
    TableRow,
    TableCell,
    WidthType,
    AlignmentType,
    HeadingLevel,
  } = await import('docx');

  const techStackRows = Object.entries(portfolio.techStack).map(([key, value]) =>
    new TableRow({
      children: [
        new TableCell({
          children: [new Paragraph(key)],
          width: { size: 30, type: WidthType.PERCENTAGE },
        }),
        new TableCell({
          children: [new Paragraph(value)],
          width: { size: 70, type: WidthType.PERCENTAGE },
        }),
      ],
    })
  );

  const featureParagraphs = portfolio.features.map(feature =>
    new Paragraph({
      bullet: { level: 0 },
      children: [new TextRun(feature)],
    })
  );

  const screenParagraphs = portfolio.screens.map((screen, idx) =>
    new Paragraph({
      numbering: { reference: 'screens', level: 0 },
      children: [new TextRun(screen)],
    })
  );

  const usageParagraphs = portfolio.usageSteps.map(step =>
    new Paragraph({
      children: [new TextRun(step)],
    })
  );

  const doc = new Document({
    numbering: {
      config: [
        {
          reference: 'screens',
          levels: [
            {
              level: 0,
              format: 'decimal',
              text: '%1.',
              alignment: AlignmentType.LEFT,
            },
          ],
        },
      ],
    },
    sections: [
      {
        properties: {},
        children: [
          new Paragraph({
            text: portfolio.name,
            heading: HeadingLevel.TITLE,
            alignment: AlignmentType.CENTER,
          }),

          new Paragraph({
            text: '기본 정보',
            heading: HeadingLevel.HEADING_1,
            spacing: { before: 400, after: 200 },
          }),

          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              new TableRow({
                children: [
                  new TableCell({
                    children: [new Paragraph('항목')],
                    width: { size: 30, type: WidthType.PERCENTAGE },
                  }),
                  new TableCell({
                    children: [new Paragraph('내용')],
                    width: { size: 70, type: WidthType.PERCENTAGE },
                  }),
                ],
              }),
              new TableRow({
                children: [
                  new TableCell({ children: [new Paragraph('분야')] }),
                  new TableCell({ children: [new Paragraph(portfolio.category.name)] }),
                ],
              }),
              new TableRow({
                children: [
                  new TableCell({ children: [new Paragraph('플랫폼')] }),
                  new TableCell({ children: [new Paragraph(portfolio.platform.toUpperCase())] }),
                ],
              }),
              new TableRow({
                children: [
                  new TableCell({ children: [new Paragraph('버전')] }),
                  new TableCell({ children: [new Paragraph(portfolio.version)] }),
                ],
              }),
              new TableRow({
                children: [
                  new TableCell({ children: [new Paragraph('생성일')] }),
                  new TableCell({
                    children: [
                      new Paragraph(
                        new Date(portfolio.createdAt).toLocaleDateString('ko-KR')
                      ),
                    ],
                  }),
                ],
              }),
            ],
          }),

          new Paragraph({
            text: '프로젝트 설명',
            heading: HeadingLevel.HEADING_1,
            spacing: { before: 400, after: 200 },
          }),

          new Paragraph({
            children: [new TextRun(portfolio.description)],
          }),

          new Paragraph({
            text: '디자인 테마',
            heading: HeadingLevel.HEADING_1,
            spacing: { before: 400, after: 200 },
          }),

          new Paragraph({
            children: [
              new TextRun({
                text: portfolio.designTheme.name,
                bold: true,
              }),
            ],
          }),

          new Paragraph({
            children: [
              new TextRun({
                text: `Background: ${portfolio.designTheme.bg}`,
              }),
            ],
          }),

          new Paragraph({
            children: [
              new TextRun({
                text: `Text: ${portfolio.designTheme.text}`,
              }),
            ],
          }),

          new Paragraph({
            children: [
              new TextRun({
                text: `Accent: ${portfolio.designTheme.accent}`,
              }),
            ],
          }),

          new Paragraph({
            text: '핵심 기능',
            heading: HeadingLevel.HEADING_1,
            spacing: { before: 400, after: 200 },
          }),

          ...featureParagraphs,

          new Paragraph({
            text: '기술 스택',
            heading: HeadingLevel.HEADING_1,
            spacing: { before: 400, after: 200 },
          }),

          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: techStackRows,
          }),

          new Paragraph({
            text: '화면 구성',
            heading: HeadingLevel.HEADING_1,
            spacing: { before: 400, after: 200 },
          }),

          ...screenParagraphs,

          new Paragraph({
            text: '사용 방법',
            heading: HeadingLevel.HEADING_1,
            spacing: { before: 400, after: 200 },
          }),

          ...usageParagraphs,

          new Paragraph({
            children: [
              new TextRun({
                text: `Portfolio #${portfolio.number}`,
                italics: true,
              }),
            ],
            spacing: { before: 400 },
          }),

          new Paragraph({
            children: [
              new TextRun({
                text: 'Generated by Portfolio Generator',
                italics: true,
              }),
            ],
          }),
        ],
      },
    ],
  });

  return doc;
}

export function generatePlainText(portfolio: Portfolio): string {
  const techStackStr = Object.entries(portfolio.techStack)
    .map(([key, value]) => `${key}: ${value}`)
    .join('\n');

  const featuresStr = portfolio.features
    .map((f, i) => `${i + 1}. ${f}`)
    .join('\n');

  const screensStr = portfolio.screens
    .map((s, i) => `${i + 1}. ${s}`)
    .join('\n');

  return `===============================================
${portfolio.name}
===============================================

분야: ${portfolio.category.name}
플랫폼: ${portfolio.platform.toUpperCase()}
버전: ${portfolio.version}
생성일: ${new Date(portfolio.createdAt).toLocaleDateString('ko-KR')}

-----------------------------------------------
[프로젝트 설명]
-----------------------------------------------
${portfolio.description}

-----------------------------------------------
[디자인 테마]
-----------------------------------------------
${portfolio.designTheme.name}
- Background: ${portfolio.designTheme.bg}
- Text: ${portfolio.designTheme.text}
- Accent: ${portfolio.designTheme.accent}

-----------------------------------------------
[핵심 기능]
-----------------------------------------------
${featuresStr}

-----------------------------------------------
[기술 스택]
-----------------------------------------------
${techStackStr}

-----------------------------------------------
[화면 구성]
-----------------------------------------------
${screensStr}

-----------------------------------------------
[사용 방법]
-----------------------------------------------
${portfolio.usageSteps.join('\n')}

===============================================
Portfolio #${portfolio.number}
Generated by Portfolio Generator
===============================================`;
}
